        name: CICD_TEST

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            
undefined