name: JMETER

on:
  workflow_dispatch:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

  JMETER:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Write Script Content to cicd.jmx
        run: |
          sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@158.220.107.63 'echo "testdata" > /root/projects/jmeter/cicd.jmx'
          
      - name: JMeter and Run Test
        run: |
          sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@158.220.107.63 << EOF
            cd /root/projects/jmeter/apache-jmeter-5.4.1/bin
            ./jmeter.sh -n -t /root/projects/jmeter/test.jmx -l /root/projects/jmeter/results.jtl
          EOF
