        name: Runner_100

        on:
          workflow_dispatch:
  

        jobs:
          build:
           name: GITHUB
           runs-on: [self-hosted, windows]
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            


        #---------------------Docker
          DOCKERHUB:
            needs : [build]
            runs-on: [self-hosted, windows]
            steps:
                - name: Checkout code
                  uses: actions/checkout@v2
                
                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v3
                
                - name: Login to Docker Hub
                  uses: docker/login-action@v2
                  with:
                    username: suriyakanth1
                    password: dckr_pat_LSDYW7uqWPPYvQOrLJFEbl7oPjM
                - name: Build and push
                  uses: docker/build-push-action@v5
                  with:
                      push: true
                      tags: suriyakanth1/dockerimagebuild:main
            

