        name: Runners _31

        on:
          workflow_dispatch:
  
[object Promise]


        #---------------- Docker
          DOCKERHUB:
            needs : [build]
            runs-on: ubuntu-latest
            steps:
                - name: Checkout code
                  uses: actions/checkout@v2
                
                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v3
                
                - name: Login to Docker Hub
                  uses: docker/login-action@v2
                  with:
                    username: suriyakanth1
                    password: dckr_pat_LSDYW7uqWPPYvQOrLJFEbl7oPjM
                - name: Build and push
                  uses: docker/build-push-action@v5
                  with:
                      push: true
                      tags: suriyakanth1/dockerimagebuild:main
            

