        name: Sample_Script-1

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            


        #---------------- Docker
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           environment:
              name: DEVELOPMENT
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: ${{ vars.DEV_DOCKER_USERNAME }}
                 password: ${{ secrets.DEV_DOCKER_ACCESSTOKEN }}
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: ${{ vars.DEV_DOCKER_USERNAME }}/dockerimagebuild:main

    #---------------- sonarqube
          SONARQUBE:
            needs: [DOCKERHUB]
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            steps:
              - uses: actions/checkout@master
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: ${{ secrets.DEV_SONAR_ACCESSTOKEN }}
                SONAR_HOST_URL: ${{ vars.DEV_SONAR_URL }}
