        name: Test_19-06 

        on:
          workflow_dispatch:
          push:
           paths-ignore:
             - '.github/workflows/**'
             - '**/Dockerfile'
             - '**/sonar-project.properties'
  

        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

        #---------------- DOCKER
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: mdriyasm7
                 password: dckr_pat_Y5xgEZ4xVVZlMKs_EbeYVSvyakk
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: mdriyasm7/dockerimagebuild:main
            