        name: Test-25-71

        on:
          workflow_dispatch:
  

        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            


        #---------------- Docker
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: null
                 password: dckr_pat_LSDYW7uqWPPYvQOrLJFEbl7oPjM
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: null/dockerimagebuild:main
            

    #---------------- sonarqube
          SONARQUBE:
            needs: [DOCKERHUB]
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@master
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: squ_8c5e7438e05474ebcb879b70892d439619fe4daa
                SONAR_HOST_URL: http://158.220.107.63:9000/

      #---------------- VM
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            needs: [SONARQUBE]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3

               - name: Deploy to Linux Server
                 run: |
                     sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@null"docker pull null/dockerimagebuild:main && docker run --rm -p 3000:3000 -d null/dockerimagebuild:main"