        name: TEST_DEMO

        on:
          workflow_dispatch:
          push:
           paths-ignore:
             - '.github/workflows/**'
             - '**/Dockerfile'
             - '**/sonar-project.properties'
  

        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            
 
    #---------------- Orchestration 
          ORCHESTRATION:
            needs: [build]
            runs-on: ubuntu-latest
            timeout-minutes: 720
            permissions:
               issues: write
            steps:
               - uses: trstringer/manual-approval@v1
                 with:
                   secret: ${{ secrets.GITHUB_TOKEN }}
                   approvers: suriyakanth1
                   issue-title: "Orchestration"
                   issue-body: "run_id: ${{ github.run_id }}"
